import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { supabase } from "../utils/supabase";
import { format, compareAsc } from "date-fns";
import CharactersCard from "../components/CharactersCard";
import WeaponsCard from "../components/WeaponsCard";

interface FarmableProps {
  characters: {
    id: number;
    name: string;
    icon: string;
    splash: string;
    farmable_days: string[];
  }[];
  weapons: {
    id: number;
    name: string;
    image: string;
    farmable_days: string[];
  }[];
  today: string;
}

const Home: NextPage<FarmableProps> = ({ characters, weapons }) => {
  let today = format(new Date(), "EEEE");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1>Uwu</h1>
        <CharactersCard characters={characters} today={today} />
        <WeaponsCard weapons={weapons} today={today} />
      </main>
    </>
  );
};

export const getStaticProps = async () => {
  const { data: characters } = await supabase.from("characters").select("*");
  const { data: weapons } = await supabase.from("weapons").select("*");

  return {
    props: {
      characters,
      weapons,
    },
  };
};

export default Home;
