import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { supabase } from "../utils/supabase";
import { format, compareAsc } from "date-fns";
import CharactersContainer from "../components/CharactersContainer";
import WeaponsContainer from "../components/WeaponsContainer";
import TodayCard from "../components/TodayCard";
import Navbar from "../components/Navbar";
import { useState } from "react";
import TodoList from "../components/Todos/TodoList";

interface FarmableProps {
  characters: {
    id: number;
    name: string;
    icon: string;
    splash: string;
    farmable_days: string[];
  }[];
  weapons: {
    id: number;
    name: string;
    image: string;
    farmable_days: string[];
  }[];
  today: string;
  farmingCharacters: {
    id: number;
    name: string;
    icon: string;
    splash: string;
    farmable_days: string[];
  }[];
}

const Home: NextPage<FarmableProps> = ({ characters, weapons }) => {
  let today = format(new Date(), "EEEE");
  let [farmingCharacters, setFarmingCharacters] = useState<
    FarmableProps["farmingCharacters"]
  >([]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col items-center justify-center border-2 border-green-500">
        <TodayCard today={today} />
        <CharactersContainer characters={characters} today={today} />
        <WeaponsContainer weapons={weapons} today={today} />
        <TodoList
          farmingCharacters={farmingCharacters}
          setFarmingCharacters={setFarmingCharacters}
        />
      </main>
    </>
  );
};

export const getStaticProps = async () => {
  const { data: characters } = await supabase.from("characters").select("*");
  const { data: weapons } = await supabase.from("weapons").select("*");

  return {
    props: {
      characters,
      weapons,
    },
  };
};

export default Home;
